# SPDX-License-Identifier: Apache-2.0
"""My Daemon — cross-platform bootstrap helper.

Run me from the project root to:
  1. Verify Python version
  2. Create a .venv (uses uv if available, else stdlib venv + pip)
  3. Install the project in editable mode with dev extras
  4. Copy config.example.yaml -> config.yaml and .env.example -> .env (if missing)
  5. Print next steps with the activate command for your OS

Usage:
  Windows:   double-click setup.bat   (or:  python setup.py)
  Linux/Mac: python setup.py

NOTE: This is *not* a setuptools build script. The project's actual build
system is hatchling, configured in pyproject.toml. This file is a
project-level convenience bootstrap and is ignored by pip during builds.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import NoReturn

MIN_PY = (3, 11)
ROOT = Path(__file__).resolve().parent
VENV_DIR = ROOT / ".venv"

IS_WINDOWS = os.name == "nt"


def section(msg: str) -> None:
    print(f"\n=== {msg} ===")


def info(msg: str) -> None:
    print(f"  - {msg}")


def warn(msg: str) -> None:
    print(f"  ! {msg}")


def fail(msg: str, code: int = 1) -> NoReturn:
    print(f"\n[ERROR] {msg}", file=sys.stderr)
    sys.exit(code)


def check_python_version() -> None:
    section(f"Python version (need >= {MIN_PY[0]}.{MIN_PY[1]})")
    if sys.version_info < MIN_PY:
        fail(
            f"Found Python {sys.version_info.major}.{sys.version_info.minor}. "
            f"Install Python {MIN_PY[0]}.{MIN_PY[1]}+ from https://www.python.org/downloads/."
        )
    info(f"OK — Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")


def venv_python() -> Path:
    if IS_WINDOWS:
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python"


def have_uv() -> bool:
    return shutil.which("uv") is not None


def create_venv() -> None:
    section("Virtual environment (.venv)")
    if VENV_DIR.exists():
        info(f"Reusing existing .venv at {VENV_DIR}")
        return

    if have_uv():
        info("Found uv on PATH — using `uv venv`")
        subprocess.run(["uv", "venv", str(VENV_DIR)], check=True, cwd=ROOT)
    else:
        info("uv not found — using stdlib `python -m venv`")
        subprocess.run([sys.executable, "-m", "venv", str(VENV_DIR)], check=True, cwd=ROOT)
    info(f"Created {VENV_DIR}")


def install_deps() -> None:
    section("Install project dependencies (editable + [dev])")
    target = ".[dev]"
    if have_uv():
        info("Using `uv pip install` (faster)")
        subprocess.run(
            ["uv", "pip", "install", "--python", str(venv_python()), "-e", target],
            check=True,
            cwd=ROOT,
        )
    else:
        info("Using the venv's pip")
        py = str(venv_python())
        # Ensure pip is current; new venvs sometimes ship with an old pip
        subprocess.run([py, "-m", "ensurepip", "--upgrade"], check=False, cwd=ROOT)
        subprocess.run([py, "-m", "pip", "install", "--upgrade", "pip"], check=True, cwd=ROOT)
        subprocess.run([py, "-m", "pip", "install", "-e", target], check=True, cwd=ROOT)
    info("Dependencies installed")


def copy_template(src_name: str, dest_name: str) -> None:
    src = ROOT / src_name
    dest = ROOT / dest_name
    if not src.is_file():
        warn(f"Missing template {src_name} — skipping")
        return
    if dest.exists():
        info(f"{dest_name} already exists — leaving it alone")
        return
    shutil.copy(src, dest)
    info(f"Created {dest_name} from {src_name}")


def seed_configs() -> None:
    section("Configuration files")
    copy_template("config.example.yaml", "config.yaml")
    copy_template(".env.example", ".env")


# CRLF line endings so the files are treated as proper Windows scripts.
#
# launch-gui.vbs is the *default* double-click target — wscript runs it with
# WindowStyle=0 (hidden) and Wait=False (return immediately), so no console
# window ever appears. launch-gui.bat is the *debug* fallback: it leaves the
# console open and forces --no-native so stdout is visible.
_LAUNCH_GUI_VBS = (
    "' My Daemon - silent launcher for the chat window.\r\n"
    "' Auto-generated by setup.py; re-run that to regenerate.\r\n"
    "' Double-click this file: pywebview window appears, no console.\r\n"
    "' Stdout/stderr are redirected to %LOCALAPPDATA%\\my-daemon\\daemon.log;\r\n"
    "' non-zero exit pops a MsgBox pointing at that log.\r\n"
    "\r\n"
    "Option Explicit\r\n"
    "Dim shell, fso, root, exePath, logDir, logPath, cmd, exitCode\r\n"
    'Set fso = CreateObject("Scripting.FileSystemObject")\r\n'
    "root = fso.GetParentFolderName(WScript.ScriptFullName)\r\n"
    'exePath = root & "\\.venv\\Scripts\\daemon.exe"\r\n'
    "If Not fso.FileExists(exePath) Then\r\n"
    '    MsgBox ".venv\\Scripts\\daemon.exe not found." & vbCrLf & _\r\n'
    '        "Run setup.bat first to bootstrap the project.", _\r\n'
    '        vbCritical, "My Daemon"\r\n'
    "    WScript.Quit 1\r\n"
    "End If\r\n"
    'Set shell = CreateObject("WScript.Shell")\r\n'
    "shell.CurrentDirectory = root\r\n"
    'logDir = shell.ExpandEnvironmentStrings("%LOCALAPPDATA%") & "\\my-daemon"\r\n'
    "If Not fso.FolderExists(logDir) Then fso.CreateFolder(logDir)\r\n"
    'logPath = logDir & "\\daemon.log"\r\n'
    "' cmd /c lets us redirect stdout+stderr. Without this, any import-time\r\n"
    "' Python error vanishes (the window is hidden).\r\n"
    'cmd = "cmd /c """ & exePath & """ chat 1>>""" & logPath & """ 2>&1"\r\n'
    "' WindowStyle = 0 (hidden), Wait = True so we can react to a fast crash.\r\n"
    "exitCode = shell.Run(cmd, 0, True)\r\n"
    "If exitCode <> 0 Then\r\n"
    '    MsgBox "My Daemon exited with code " & exitCode & "." & vbCrLf & _\r\n'
    '        "Log: " & logPath, vbExclamation, "My Daemon"\r\n'
    "End If\r\n"
)

_LAUNCH_GUI_BAT = (
    "@echo off\r\n"
    "REM My Daemon - DEBUG launcher (visible console, browser tab).\r\n"
    "REM Use launch-gui.vbs for the normal silent desktop-window launch.\r\n"
    "REM This file is auto-generated by setup.py.\r\n"
    "\r\n"
    "setlocal\r\n"
    'cd /d "%~dp0"\r\n'
    "\r\n"
    'if not exist ".venv\\Scripts\\daemon.exe" (\r\n'
    "    echo [ERROR] .venv\\Scripts\\daemon.exe not found.\r\n"
    "    echo Run setup.bat first to bootstrap the project.\r\n"
    "    pause\r\n"
    "    exit /b 1\r\n"
    ")\r\n"
    "\r\n"
    "echo Launching My Daemon chat (debug, browser mode)...\r\n"
    "echo Close this window or press Ctrl+C to stop the daemon.\r\n"
    "echo.\r\n"
    "\r\n"
    "REM --no-native forces the browser tab so stdout flows here. For the\r\n"
    "REM normal native-window UX, double-click launch-gui.vbs instead.\r\n"
    ".venv\\Scripts\\daemon.exe chat --no-native\r\n"
    "\r\n"
    "if %ERRORLEVEL% NEQ 0 (\r\n"
    "    echo.\r\n"
    "    echo [ERROR] daemon chat exited with code %ERRORLEVEL%.\r\n"
    "    pause\r\n"
    ")\r\n"
    "endlocal\r\n"
)


def write_gui_launcher() -> None:
    section("GUI launchers (launch-gui.vbs, launch-gui.bat)")
    vbs_target = ROOT / "launch-gui.vbs"
    vbs_target.write_bytes(_LAUNCH_GUI_VBS.encode("utf-8"))
    info(f"Wrote {vbs_target.name} — double-click on Windows for a silent native chat window.")
    bat_target = ROOT / "launch-gui.bat"
    bat_target.write_bytes(_LAUNCH_GUI_BAT.encode("utf-8"))
    info(f"Wrote {bat_target.name} — debug launcher (visible console, browser tab).")


_LAUNCH_SETUP_BAT = (
    "@echo off\r\n"
    "REM My Daemon - launch the setup window (vault picker + API key).\r\n"
    "REM Auto-generated by setup.py; re-run that to regenerate.\r\n"
    "\r\n"
    "setlocal\r\n"
    'cd /d "%~dp0"\r\n'
    "\r\n"
    'if not exist ".venv\\Scripts\\daemon.exe" (\r\n'
    "    echo [ERROR] .venv\\Scripts\\daemon.exe not found.\r\n"
    "    echo Run setup.bat first to bootstrap the project.\r\n"
    "    pause\r\n"
    "    exit /b 1\r\n"
    ")\r\n"
    "\r\n"
    "echo Opening My Daemon setup window...\r\n"
    ".venv\\Scripts\\daemon.exe setup\r\n"
    "\r\n"
    "if %ERRORLEVEL% NEQ 0 (\r\n"
    "    echo.\r\n"
    "    echo [ERROR] daemon setup exited with code %ERRORLEVEL%.\r\n"
    "    pause\r\n"
    ")\r\n"
    "endlocal\r\n"
)


def write_setup_launcher() -> None:
    section("Setup launcher (launch-setup.bat)")
    target = ROOT / "launch-setup.bat"
    target.write_bytes(_LAUNCH_SETUP_BAT.encode("utf-8"))
    info(f"Wrote {target.name} — double-click on Windows to set the vault + API key.")


# ---------------------------------------------------------------- POSIX launchers
#
# Linux: my-daemon.desktop is the GNOME / KDE / etc. launcher; copy it to
#   ~/.local/share/applications/ to make the daemon appear in the activities menu.
# macOS: launch-gui.command runs from a Finder double-click. Terminal may
#   briefly appear; wrap in an AppleScript .app to suppress entirely.
# Both share launch-gui.sh as the underlying shell entry point.

_LAUNCH_GUI_SH = (
    "#!/usr/bin/env bash\n"
    "# My Daemon - launcher for the chat window (Linux / macOS).\n"
    "# Auto-generated by setup.py; re-run that to regenerate.\n"
    "set -e\n"
    'SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"\n'
    'cd "$SCRIPT_DIR"\n'
    "if [ ! -x .venv/bin/daemon ]; then\n"
    '  echo "[ERROR] .venv/bin/daemon not found. Run python setup.py first." >&2\n'
    "  exit 1\n"
    "fi\n"
    'exec ./.venv/bin/daemon chat "$@"\n'
)


def _desktop_entry(launcher_path: Path) -> str:
    """freedesktop.org entry pointing at the absolute path of launch-gui.sh."""
    return (
        "[Desktop Entry]\n"
        "Type=Application\n"
        "Name=My Daemon\n"
        "GenericName=Personal memory companion\n"
        "Comment=Ask your vault — RAG + graph over your Obsidian notes\n"
        f"Exec={launcher_path}\n"
        "Terminal=false\n"
        "Categories=Utility;Office;\n"
        "Keywords=daemon;obsidian;rag;memory;\n"
        "StartupWMClass=My Daemon\n"
    )


def write_posix_launchers() -> None:
    """Emit launch-gui.sh, my-daemon.desktop, launch-gui.command on POSIX."""
    section("POSIX launchers (launch-gui.sh, my-daemon.desktop, launch-gui.command)")
    sh_target = ROOT / "launch-gui.sh"
    sh_target.write_text(_LAUNCH_GUI_SH, encoding="utf-8", newline="\n")
    sh_target.chmod(sh_target.stat().st_mode | 0o111)  # +x for owner/group/other
    info(f"Wrote {sh_target.name} (+x) — generic shell launcher.")

    desktop_target = ROOT / "my-daemon.desktop"
    desktop_target.write_text(_desktop_entry(sh_target.resolve()), encoding="utf-8", newline="\n")
    info(
        f"Wrote {desktop_target.name} — Linux desktop entry. "
        f"Copy to ~/.local/share/applications/ to surface in the menu."
    )

    command_target = ROOT / "launch-gui.command"
    command_target.write_text(_LAUNCH_GUI_SH, encoding="utf-8", newline="\n")
    command_target.chmod(command_target.stat().st_mode | 0o111)
    info(f"Wrote {command_target.name} (+x) — macOS Finder-launchable shim.")


def print_next_steps() -> None:
    section("Next steps")
    activate = r".venv\Scripts\activate.bat" if IS_WINDOWS else "source .venv/bin/activate"

    print(
        f"""
  1. Run the setup window to pick your vault and set your API key:

       daemon setup
       (Windows users can double-click launch-setup.bat instead.)

  2. Start Qdrant (one-time per machine):

       docker compose up -d

  3. Activate the environment in your shell:

       {activate}

  4. Ingest your vault and ask your first question:

       daemon ingest -v
       daemon query "what was I thinking about last week"

  5. Launch the chat GUI:

       daemon chat
       Windows:  double-click launch-gui.vbs   (silent native window)
                 launch-gui.bat                 (debug: visible console)
       Linux:    cp my-daemon.desktop ~/.local/share/applications/
                 …or just run ./launch-gui.sh
       macOS:    double-click launch-gui.command

  Full reference: README.md
"""
    )


def main() -> int:
    print("My Daemon — bootstrap")
    print(f"Project root: {ROOT}")
    try:
        check_python_version()
        create_venv()
        install_deps()
        seed_configs()
        if IS_WINDOWS:
            write_gui_launcher()
            write_setup_launcher()
        else:
            write_posix_launchers()
        print_next_steps()
    except subprocess.CalledProcessError as exc:
        fail(f"Command failed: {exc.cmd} (exit {exc.returncode})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
